version: '3'
services:
  challenge:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    working_dir: /home/pwn
    container_name: uheap
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "1337:9999"
    entrypoint: /etc/init.sh
    init: true
    restart: always
